rds/postgres/README.md
rds/postgres/example/main.tf
rds/postgres/main.tf
rds/postgres/outputs.tf
rds/postgres/variables.tf

Moved the responsibility for generating random master credentials to the user of `rds/postgres`.
This is due to an issue with `count` when a variable value is provided by a resource attribute, eg. 
```tf
resource "random_string" "foo" {
length = 8
}
resource "random_string" "bar" {
count = random_string.foo.result != null ? 1 : 0
length = 8
}
```
will fail with
```
Error: Invalid count argument
on main.tf line 6, in resource "random_string" "bar":
6:   count  = random_string.foo.result != null ? 1 : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
because terraform isn't smart …

breaking(rds/postgres): require master credentials

---

ssl/acm/README.md
ssl/acm/example/main.tf
ssl/acm/main.tf
ssl/acm/outputs.tf

feat(ssl/acm): Added validated_arn output

---

ecs/example/main.tf
ecs/repository/README.md
ecs/repository/main.tf
ecs/repository/variables.tf

ECR repositories are meant to be created one per image, as in you can only add tags. To reflect that, added an `image_name` variable which is appended to the repository name.
Both of the above are breaking changes.

refactor(ecs/repository)!: added image_name variable

---

ecs/task/log_group/main.tf
ecs/task/log_group/outputs.tf
ecs/task/main.tf
spa/main.tf
ssl/acm/outputs.tf

Fixes issues with conditional resource creation (eg. `var.create`) found by Terraform >= 0.12.11
https://github.com/hashicorp/terraform/issues/23222
There might be more of these hidden somewhere in the code, we'll deal with the rest of them as they surface...

fix: is empty tuple errors on terraform >=0.12.11

---

ses/domain/README.md
ses/domain/main.tf
ses/domain/outputs.tf
ses/domain/variables.tf

We need a way to provide custom TXT & MX records in order to verify domain for third party like G Suite. It would probably be used as follows:
```
module "ses_domain" {
source = "github.com/codequest-eu/terraform-modules?ref=xxx//ses/domain"
create = var.create
providers = {
aws = aws.ses
}
txt_records = ["google-site-verification=xxx"]
mx_records = [
"1 ASPMX.L.GOOGLE.COM",
"5 ALT1.ASPMX.L.GOOGLE.COM",
"5 ALT2.ASPMX.L.GOOGLE.COM",
"10 ALT3.ASPMX.L.GOOGLE.COM",
"10 ALT4.ASPMX.L.GOOGLE.COM",
]
}
```

feat(ses/domain): added mx_records variable and spf_record output

---

ecs/services/web/main.tf

ECS services associated with a target group have to be created after that target group is associated with a load balancer. Otherwise AWS throws:
> Error: InvalidParameterException: The target group with targetGroupArn (...) does not have an associated load balancer.

fix(ecs/services/web): service created too early

---

ecs/host_group/main.tf

Switched to `name_prefix` for `aws_launch_configuration` so it can be updated with `create_before_destroy`.
AWS Launch Configurations are immutable, so you need to create a new one with the desired changes every time. By default terraform first tries to remove the old configuration and then create a new one to avoid name collisions, however that fails, because the old configuration is still attached to the auto scaling group. We need to create a new one first, update the auto scaling group and then remove the old configuration.

fix(ecs/host_group): unable to update launch configuration

---

ecs/network/main.tf

chore(ecs/network): updated NAT instance AMI

---

ecs/host_group/README.md
ecs/host_group/main.tf
ecs/host_group/templates/user_data.sh
ecs/host_group/variables.tf

feat(ecs/host_group): added detailed_monitoring variable

---

ecs/host_group/main.tf

feat(ecs/host_group): added autoscaling group metrics

---

ecs/host_group/templates/user_data.sh

Known issues:
- fixed in 756c679: the ECS agent might not be fully up to date initially, for some reason `docker pull amazon/amazon-ecs-agent:latest` doesn't seem to work as expected when run from the user data script. When you ssh into an instance and run `docker pull` it will say that there was a newer image, even though it should have already been pulled. 
Closes #52 
Closes #53

feat(ecs/host_group): automatic updates

---

ecs/host_group/main.tf

To do:
- remove the launch configuration in a separate PR, for some reason terraform tries to remove it before switching the ASG to the launch template which results in a failure
https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html

refactor(ecs/host_group): switch from launch configuration to a launch template

---

ecs/host_group/README.md
ecs/host_group/main.tf
ecs/host_group/variables.tf

**BREAKING CHANGES**: 
- Launch template now defaults to `standard` cpu credits regardless of instance_type. If you were using t3* instances this used to be `unlimited`, so you might need to either add `cpu_credits = "unlimited"` or update your instances
Closes #42 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html

feat(ecs/host_group)!: added cpu_credits variable

---

ecs/host_group/README.md
ecs/host_group/main.tf
ecs/host_group/variables.tf

**BREAKING CHANGES**:
- reverted `cpu_credits` default value back to AWS default, which reverts the breaking change from #57

fix(ecs/host_group)!: reverted cpu credits defaults

---

ecs/network/main.tf

AWS CLI requires `AWS_DEFAULT_REGION` environment variable and ignores `AWS_REGION`
Bug was introduced in b2b6b8574ec9036cd03c150a25b75fb320f27abe

fix(ecs/network): SSM agents restart fails with "You must specify a region"

---

ecs/host_group/templates/user_data.sh

By default ECS agent removes stopped containers after 3 hours, which is nice for debugging, but can also kill an instance if a task creates some files, fails and is restarted over and over, filling up the whole disk.
Lowered the wait time to 5 minutes to minimize the chance of that happening.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

fix(ecs/host_group): stopped containers overflow

---

ecs/host_group/README.md
ecs/host_group/main.tf
ecs/host_group/templates/user_data.sh
ecs/host_group/variables.tf

feat(ecs/host_group): enabled instance user data customization

---

ecs/host_group/templates/user_data.sh

fix(ecs/host_group): reserve some memory for system processes

---

Jenkinsfile

fix(ci): jenkins github autostatus creating too many statuses

---

cloudwatch/metric/many/README.md
cloudwatch/metric/many/main.tf
cloudwatch/metric/many/outputs.tf
cloudwatch/metric/many/variables.tf
cloudwatch/metric/many/versions.tf
cloudwatch/metric_expression/many/README.md
cloudwatch/metric_expression/many/main.tf
cloudwatch/metric_expression/many/outputs.tf
cloudwatch/metric_expression/many/variables.tf
cloudwatch/metric_expression/many/versions.tf
cloudwatch/metric_widget/example/main.tf

Needed for #71 to create metrics for a variable number of NAT instances

feat(cloudwatch): added modules for creating many metrics at once

---

ses/domain/example/main.tf
ssl/acm/example/main.tf

docs: removed codequest.com from examples

---

ecs/example/main.tf
ecs/host_group/README.md
ecs/host_group/metrics.tf
ecs/host_group/outputs.tf
ecs/host_group/widgets.tf

- min, max, desired instance count
- instance count by state
- memory, swap, cpu, root filesystem utilization (min, average, max)
- cpu credit balance
- root filesystem free space (min, max, average)
- filesystem and network IO
- scaling
- breakdown of instance counts by state
- memory, swap, cpu, root filesystem utilization
- cpu credit balance
- root filesystem free space
- filesystem and network IO
Example dashboard:
Related to #43

feat(ecs/host_group): cloudwatch metrics and dashboard widgets

---

cloudwatch/metric/main.tf
cloudwatch/metric/many/main.tf
ses/domain/README.md
ses/domain/example/bin/spammer
ses/domain/example/bin/spammer.py
ses/domain/example/main.tf
ses/domain/main.tf
ses/domain/metrics.tf
ses/domain/outputs.tf
ses/domain/widgets.tf

- sent/delivered/bounced counters
- sent/delivered/bounced percentages
- open/click counters
- open/click percentages
- counts breakdown by delivery status (delivered, bounced, rejected, etc.)
- percentages breakdown by delivery status
- conversion (sent, delivered, opened, clicked)
- account bounce and spam reputation
Example dashboard:
Related to #43

feat(ses/domain): cloudwatch metrics and dashboard widgets

---

Jenkinsfile
ssl/acm/variables.tf
tools/bin/check-docs

Refactored the CI pipeline so it doesn't try to do as many parallel tasks. Previously we would run, eg. `terraform validate` for each module in parallel, which caused some random memory usage problems. 
Now the pipeline looks like this:
and you can drill down to individual modules/examples by just clicking on one of the stages:

fix(build): random CI out of memory errors due to over-parallelization

---

terraform/backend/s3/README.md
terraform/backend/s3/example/main.tf
terraform/backend/s3/main.tf
terraform/backend/s3/outputs.tf
terraform/backend/s3/variables.tf
terraform/backend/s3/versions.tf

Overlaps in functionality with the `meta` module, which we could, and probably should, deprecate going forward, since it assumes a bit too many things.

feat: added terraform/backend/s3 module

---

spa/examples/development/main.tf
spa/main.tf

Added a cloudfront behavior for `.well-known/*` which serves assets from `.well-known` without requiring basic authentication. `.well-known` is used by third party services to fetch information about the domain and as such has to be accessible without authentication.

feat(spa): added .well-known/* behavior that doesn't require basic auth

---

ecs/task/README.md
ecs/task/log_group/README.md
ecs/task/log_group/main.tf
ecs/task/log_group/variables.tf
ecs/task/main.tf
ecs/task/variables.tf

feat(ecs/task)!: Added log_retention variable

---

rds/postgres/README.md
rds/postgres/example/bin/psql
rds/postgres/main.tf
rds/postgres/variables.tf

When `auto_minor_version_upgrade` is set to `true` (which is the default) the database is automatically upgraded from time to time. This changes are not reflected in Terraform state though, which can lead to unexpected bugs on `terraform apply`, e.g.
`Cannot upgrade postgres from 10.13 to 10.6`
This PR sets explicit `false` to `auto_minor_version_upgrade` and updates default `postgres_version`.

 fix(rds/postgres): disable auto_minor_version_upgrade

---

ssl/acm/README.md
ssl/acm/example/main.tf
ssl/acm/main.tf
ssl/acm/outputs.tf
ssl/acm/variables.tf
ssl/acm/versions.tf

feat(ssl/acm)!: support for aws provider 3.0 and manual validation

---

ecs/README.md
ecs/main.tf
ecs/network/README.md
ecs/network/main.tf
ecs/network/variables.tf
ecs/variables.tf

feat(ecs): added enable_dns_support and enable_dns_hostnames variables

---

cloudfront/README.md
cloudfront/main.tf
cloudfront/variables.tf
spa/README.md
spa/main.tf
spa/variables.tf

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html

feat: added ssl policy variables to cloudfront and spa

---

ses/domain/main.tf

Fixes
```
Error: invalid value for cloudwatch_destination.0.default_value (must contain only alphanumeric, underscore, and hyphen characters)
```

fix(ses): invalid event destination default value

---

cloudfront/examples/response_headers/main.tf
cloudfront/invalidation/README.md
cloudfront/invalidation/main.tf
cloudfront/invalidation/variables.tf
cloudfront/invalidation/versions.tf
cloudfront/lambda/main.tf
cloudfront/lambda/response_headers/README.md
cloudfront/lambda/response_headers/dist/index.js
cloudfront/lambda/response_headers/dist/index.js.license
cloudfront/lambda/response_headers/main.tf
cloudfront/lambda/response_headers/outputs.tf
cloudfront/lambda/response_headers/src/.gitignore
cloudfront/lambda/response_headers/src/index.ts
cloudfront/lambda/response_headers/src/package-lock.json
cloudfront/lambda/response_headers/src/package.json
cloudfront/lambda/response_headers/src/tsconfig.json
cloudfront/lambda/response_headers/variables.tf
cloudfront/lambda/response_headers/versions.tf

Added a module for defining custom response headers using lambda@edge, based on
https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/

feat(cloudfront): added lambda which adds response headers

---

cloudfront/examples/basic/main.tf
cloudfront/examples/basic_auth/main.tf
cloudfront/examples/single_page_app/main.tf
cloudfront/origin/s3/README.md
cloudfront/origin/s3/main.tf
cloudfront/origin/s3/outputs.tf
cloudfront/origin/s3/variables.tf

BREAKING CHANGES:
- removed `bucket_regional_domain_name` variable
Bucket regional domain name is now built using a simple string interpolation. Using `bucket_regional_domain_name` for buckets that should be created in the same terraform apply caused errors that `count` cannot be computed at plan time.

feat!(cloudfront/origin/s3): removed bucket_regional_domain_name

---

cloudfront/lambda/README.md
cloudfront/lambda/main.tf
cloudfront/lambda/response_headers/main.tf
cloudfront/lambda/variables.tf

fix(cloudfront/lambda): default timeout exceeds cloudfront maximum for viewer events

---

ses/domain/README.md
ses/domain/main.tf
ses/domain/variables.tf

Added `mx` boolean variable to `ses/domain` module, which lets the user disable creating `MX` records.

feat(ses/domain): added the option to disable creating the MX record

---

ecs/task/role/outputs.tf

IAM role created by `ecs/task/role` could have been assigned to an ECS task before policies have been added to the role. This could result in some nasty race conditions, e.g. ECS failing to start a task due to missing permissions.
Added explicit `depends_on` to the `name` and `arn` outputs to ensure policies are assigned before the role is used.

fix(ecs/task/role): role could be used before policies have been assigned

---

ecs/network/README.md
ecs/network/main.tf
ecs/network/versions.tf
versions.tf

TLS provider 4 has removed the `key_algorithm` attribute from `tls_self_signed_cert` resource, which was required before version 3.2. This PR removes this attribute from the `ecs/network` module, so that we can upgrade to the latest TLS provider.

feat(ecs/network): support tls provider 4.x, drop support for <3.2

---

meta/main.tf
redirect/main.tf
spa/main.tf
terraform/backend/s3/main.tf

Enabled server side encryption for all buckets in all modules.
AWS has switched on server side encryption by default and for existing buckets, so this was just causing mismatches between states and actual AWS configuration.

feat: enable default server side encryption for S3 buckets

---

cloudfront/lambda/README.md
cloudfront/lambda/basic_auth/main.tf
cloudfront/lambda/pull_request_router/main.tf
cloudfront/lambda/response_headers/main.tf
cloudfront/lambda/variables.tf
lambda/README.md
lambda/bin/invoke
lambda/layer/README.md
lambda/layer/variables.tf
lambda/variables.tf
rds/postgres/management_lambda/dist/index.js
rds/postgres/management_lambda/dist/index.js.license
rds/postgres/management_lambda/main.tf
rds/postgres/management_lambda/src/index.ts
rds/postgres/management_lambda/src/package-lock.json
rds/postgres/management_lambda/src/package.json
rds/postgres/management_lambda/src/tsconfig.json
spa/middleware/README.md
spa/middleware/variables.tf

Updated default nodejs runtime from 10.x and 12.x to 18.x, which is the latest LTS release.
**Breaking change**
Breaking users of default values, check if your lambda code uses anything that was changed between node 12 and node 18.

fix!: nodejs 12.x lambda runtime is no longer supported

---

rds/postgres/management_lambda/dist/index.js
rds/postgres/management_lambda/src/index.ts

AWS has changed default postgres config to force SSL connections. Changed our management lambda to always use SSL, which should work for both old and new RDS instances.

fix(rds/postgres/management_lambda): always connect with ssl

---

ses/domain/main.tf

Set the order of DMARC options in `ses/domain` module, so that `v=` and `p=` are always first.
https://support.google.com/a/answer/10032169

fix: dmarc v and p options need to be first

---

elasticache/redis/README.md
elasticache/redis/main.tf
elasticache/redis/variables.tf

Added `apply_immediately` variable to `elasticache/redis`, which is enabled by default, to force AWS to apply changes now, instead of scheduling them for the next maintenance window.

fix(redis): apply changes immediately
